#!/bin/bash

function is_git_repository {
 git branch > /dev/null 2>&1
}

function parse_git_branch {
 # Only display git info if we're inside a git repository.
 is_git_repository || return 1

 # Capture the output of the "git status" command.
 git_status="$(git status 2> /dev/null)"
 git_stash="$(git stash list 2> /dev/null)"
 # Set color based on clean/staged/dirty.
 if [[ ${git_status} =~ "working directory clean" ]]; then
   state="${GREEN}"
 elif [[ ${git_status} =~ "Changes to be committed" ]]; then
   state="${YELLOW}"
 else
   state="${RED}"
 fi
 if [[ -n ${git_stash} ]]; then
   stash="${BRIGHT_PURPLE} stashed"
 fi

 # Set arrow icon based on status against remote.
 if [[ ${git_status} =~ "Your branch is ahead" ]]; then
   remote="↑"
 elif [[ ${git_status} =~ "Your branch is behind" ]]; then
   remote="↓"
 elif [[ ${git_status} =~ ' have diverged' ]]; then
   remote="↔"
 elif [[ ! ${git_status} =~ 'Your branch is up-to-date' ]]; then
   remote="_X_"
 fi

 # Get the name of the branch.
 branch_pattern="^On branch"
 if [[ ${git_status} =~ ${branch_pattern} ]]; then
   branch="($(git symbolic-ref -q HEAD | sed -e 's|^refs/heads/||'))"
 else
   branch="{Detached HEAD}"
 fi

 # Display the prompt.
 echo "${state}${branch}${remote}${stash}${COLOR_NONE} "
}

function user_prompt() {
  PS1="$PS1${_PROMPT_USER_COLOR}\u"
}

function host_prompt() {
  PS1="$PS1${_PROMPT_DELIM_COLOR} @ ${_PROMPT_HOST_COLOR}\h"
}

function git_prompt() {
  PS1="$PS1${_PROMPT_DELIM_COLOR}\$([[ -n \$(git branch 2> /dev/null) ]] && echo \" on \")$(parse_git_branch)"
}

function pwd_prompt() {
  PS1="$PS1${_PROMPT_DELIM_COLOR} in ${_PROMPT_PWD_COLOR}\w"
}

function last_command_prompt() {
  PS1="$PS1 ${WHITE}\n\$ ${RESET_COLOR}"
}

_PROMPT_DELIM_COLOR=$BRIGHT_BLACK
_PROMPT_USER_COLOR=$BRIGHT_BLUE
_PROMPT_HOST_COLOR=$BRIGHT_ORANGE
_PROMPT_GIT_COLOR=$GREEN
_PROMPT_GIT_DIRTY_COLOR=$RED
_PROMPT_PWD_COLOR=$BRIGHT_GREEN

function prompt(){
  PS1=""
  user_prompt
  host_prompt
  pwd_prompt
  git_prompt
  last_command_prompt
  export PS1
}
export PS2="${ORANGE}→ ${RESET_COLOR}"
export PROMPT_COMMAND=prompt
